import 'app/_styles/reset.css';
import 'app/_styles/global.css';
import { ReactNode } from 'react';
import {
  AutoLoginPresence,
  PopupWrapper,
  QueryWrapper,
  RecoilRootWrapper,
} from 'app/(route)/_providers';
import { DefaultLayout } from 'app/_components/layout';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-800 text-white">
        <QueryWrapper>
          <RecoilRootWrapper>
            <AutoLoginPresence>
              <PopupWrapper />
              <DefaultLayout>{children}</DefaultLayout>
            </AutoLoginPresence>
          </RecoilRootWrapper>
        </QueryWrapper>
      </body>
    </html>
  );
}
