import 'app/_styles/reset.css';
import StyledComponentsRegistry from 'app/_lib/registry';
import {
  QueryWrapper,
  RecoilRootWrapper,
  ThemeWrapper,
} from 'app/(route)/_providers';
import { DefaultLayout } from './_components';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryWrapper>
          <RecoilRootWrapper>
            <StyledComponentsRegistry>
              <ThemeWrapper>
                <DefaultLayout>{children}</DefaultLayout>
              </ThemeWrapper>
            </StyledComponentsRegistry>
          </RecoilRootWrapper>
        </QueryWrapper>
      </body>
    </html>
  );
}
