export const LOGINT_API = '/api/user/login';
export const JOIN_API = '/api/user/join';
export const WITHDRAWAL_API = '/api/user/withdrawal';
export const USER_SHOW_API = '/api/user/show';
export const ALBUM_API = '/api/article/album';
export const BOARD_API = '/api/list/board/{num}';
export const ARTICLE_LIST_API = '/api/list/boards'; // + {boardID}/{articleID}
export const POST_ARTICLE_API = '/api/article/write';
export const COMMENT_WRITE_API = '/api/article/write';
